spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    dialect: org.hibernate.dialect.MySQL8Dialect  # 이 항목 추가
  security:
    oauth2:
      client:
        app-id: ${KAKAO_APP_ID}
        client-id: ${KAKAO_CLIENT_ID}
        redirect-uri: ${KAKAO_REDIRECT_URI}
      provider:
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        unlink-uri: https://kapi.kakao.com/v1/user/unlink
  servlet:
    multipart:
      max-file-size: 5MB
jwt:
  secret: ${JWT}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

# aws
cloud:
  aws:
    credentials:
        instance-profile: true
    s3:
      bucket: ${MUSAI_BUCKET}
      musai-directory: ${MUSAI_DIRECTORY}
      env: ${ENVIRONMENT_DIRECTORY}
      image-url: ${MUSAI_IMAGE_URL}

    stack:
      auto: false #EC2 배포 시 필요

holiday-api:
  key: ${HOLIDAY_API_KEY}
  uri: ${HOLIDAY_API_URI}

domain: ${DOMAIN}

sentry:
  dsn: ${SENTRY_DSN}
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0


# 스프링 서버 포트
server:
  port: 8080

# gRPC 서버포트
grpc:
  server:
    port: 50051 # gRPC 서버 포트
    maxInboundMessageSize: 10485760 # 최대 메시지 크기 (10MB)
    security:
      enabled: false